# Generated by Django 5.2.1 on 2025-05-19 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('mid', 'Medium'), ('low', 'Low')], default='mid', max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
