# Generated by Django 5.2.1 on 2025-05-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_remove_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
